openapi: 3.0.3
info:
  version: 1.0.1
  title: Webz.Io Clothes Marketplace
  description: Swagger for Webz Io Clothes Marketplace Interface
  contact:
    name: Ravid Gontov
    email: rvdgntv@gmail.com

paths:
  /health:
    get:
      summary: Service status endpoint.
      description: Service status endpoint.
      responses:
        200:
          description: Success
      operationId: Health Check
  
  /Clothes-Service/authenticate:
    post:
      summary: Log in as an authenticated user
      description: Log in and recieve an authentication JWT
      operationId: authenticateUser
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/AuthenticationRequestDTO'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponseDTO'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
                
  /Clothes-Service/clothes:
    get:
      summary: retrieve a searchable list of clothing items that are offered to sale
      description: 'Get a list of clothes, use the following path parameters to refine the list: sellerName (partial name search), sellerId, garmentType, minPrice, maxPrice, size'
      operationId: getClothes
      parameters:
        - name: sellerName
          in: query
          schema:
            type: string
        - name: sellerId
          in: query
          schema:
            type: string
        - name: garmentType
          in: query
          schema:
            type: string
        - name: minPrice
          in: query
          schema:
            type: number
            format: float
        - name: maxPrice
          in: query
          schema:
            type: number
            format: float
        - name: size
          in: query
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponseDTO'
        403:
          description: User is not authorized, or is missing an auth token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
        404:
          description: Query result not found!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
  
  /Clothes-Service/publishNewGarment:
    post:
      summary: Add new garment to the market
      description: An api for a publisher to add a new garment to sale
      operationId: publishNewGarment
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/GarmentRequestDTO'
      responses:
        204:
          description: Success
        403:
          description: User is not authorized, or is missing an auth token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
      security:
        - bearerAuth: []

  /Clothes-Service/deleteGarment/{id}:
    delete:
      summary: Remove a garment from the market
      description: An api for a publisher to unlist a garment from the market
      operationId: deleteGarment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            format: int32
      responses:
        204:
          description: Success
        403:
          description: User is not authorized for the garment, or is missing an auth token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
        404:
          description: Garment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
      security:
        - bearerAuth: []
  /Clothes-Service/updateGarment/{id}:
    put:
      summary: Add a new garment to the market
      description: An api for a publisher to add a new garment to sale
      operationId: updateGarment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            format: int32
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/GarmentRequestDTO'
      responses:
        204:
          description: Success
        403:
          description: User is not authorized for the garment, or is missing an auth token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
        404:
          description: Garment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDTO'
      security:
        - bearerAuth: []
components:
  schemas:
    AuthenticationRequestDTO:
      type: object
      required:
        - 'userName'
        - 'password'
      properties:
        userName:
          type: string
          maxLength: 10
        password:
          type: string
          maxLength: 15
    AuthenticationResponseDTO:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    ErrorResponseDTO:
      type: object
      required:
        - title
        - message
      properties:
        title: 
          type: string
        message:
          type: string
  
    garmentId:
      type: number
      format: int32
      description: Internal identifier for each garment
    garmentType: 
      type: string
      maxLength: 10
      enum:
        - Pants
        - Shirt
        - Socks
        - Hat
        - Hoodie
        - TankTop
        - Shoes
    publisherId:
      type: string
      maxLength: 9
    garmentSize:
      type: string
      maxLength: 2
      enum:
        - XS
        - S
        - M
        - L
        - XL
    garmentDescription:
      type: string
      maxLength: 100
      description: Describe what are you selling?
      example: Red running shoes
    price:
      type: number
      format: float
    
    # DTOs
    PublisherDTO:
      type: object
      required:
        - id
        - fullName
        - address
      properties:
        id: 
          maxLength: 9
          type: string
          description: Publisher Id
          pattern: '^\d{9}$'
          example: 12345682
        fullName:
          maxLength: 20
          type: string
          description: The full name of the publisher
          example: Ravid Gontov
        address:
          maxLength: 30
          type: string
          description: The Address of the publisher
          example: Broadway 7 New York
        garments: 
          type: array
          items:
            $ref: '#/components/schemas/GarmentResponseDTO'
      description: Publisher for clothes items
    GarmentRequestDTO:
      type: object
      required:
        - garmentType
        - size
        - price
      properties:
        garmentType:
          $ref: '#/components/schemas/garmentType'
        garmentDescription:
          $ref: '#/components/schemas/garmentDescription'
          nullable: true
        garmentSize:
          $ref: '#/components/schemas/garmentSize'
        price:
          $ref: '#/components/schemas/price'
    GarmentResponseDTO:
      type: object
      required:
        - garmentId
        - garmentType
        - publisher
        - size
        - price
      properties:
        garmentId:
          $ref: '#/components/schemas/garmentId'
        garmentType:
          $ref: '#/components/schemas/garmentType'
        garmentDescription:
          nullable: true
          $ref: '#/components/schemas/garmentDescription'
        garmentSize:
          $ref: '#/components/schemas/garmentSize'
        price:
          $ref: '#/components/schemas/price'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT